Default: &defaults
  host: "192.168.1.106" # "*4" # any IPv4 host
  port: 80 # 3000 # 
  approot:  "http://192.168.1.106" # "http://localhost:3000"
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
